import Logo from "@/components/logo";
import PlusIcon from "@/components/PlusIcon";
import generateColors from "@/utils/generateColors";
import chroma from "chroma-js";
import _ from "lodash";
import Head from "next/head";
import { useEffect, useState } from "react";
import { CompactPicker, SketchPicker } from "react-color";

export default function Home() {
  const [palettes, setPalettes] = useState([]);
  const [seeds, setSeeds] = useState(["#F77777"]);
  const [selectedSeed, setSelectedSeed] = useState(0);
  const [selectedSwatch, setSelectedSwatch] = useState(0);
  const [hoveredSwatch, setHoveredSwatch] = useState(null);
  const [seedLabelEditor, setSeedLabelEditor] = useState(null);
  const [colorPickerActive, setColorPickerActive] = useState(0);

  // When the seed colors are updated, update full palettes
  useEffect(() => {
    setPalettes(
      _.map(seeds, (seed) => {
        if (chroma.valid(seed)) {
          return generateColors(seed);
        } else {
          return generateColors("white");
        }
      })
    );
  }, [seeds]);

  const addColor = async () => {
    await setSeeds([...seeds, "#F77777"]);
    selectSeed(seeds.length);
    setColorPickerActive(seeds.length);
  };

  const updateSeed = (e, index) => {
    let newSeeds = [...seeds];
    newSeeds[index] = e.target.value;
    setSeeds(newSeeds);
  };

  const selectSeed = (index) => {
    setSelectedSeed(index);
  };

  const selectSwatch = (index) => {
    setSelectedSwatch(index);
  };

  const hoverSwatch = (index) => {
    setHoveredSwatch(index);
  };

  const editingSeedLabel = (index) => {
    setSeedLabelEditor(index);
  };

  const updateSeedColor = (color) => {
    console.log("color to update", color.hex);
    let newSeeds = [...seeds];
    newSeeds[colorPickerActive] = color.hex;
    setSeeds(newSeeds);
  };

  const Seed = ({ index, seed }) => {
    return (
      <div className={`seed ${selectedSeed === index ? "seed--selected" : ""}`}>
        <button
          className="seed__drop"
          style={{
            background: seed,
            boxShadow:
              selectedSeed === index
                ? "inset 0.25rem 0.25rem 0 rgb(0,0,0,.25)"
                : "none",
          }}
          onClick={(e) => selectSeed(index)}
        />
        {selectedSeed === index && (
          <>
            {seedLabelEditor === index ? (
              <input
                className="seed__label-input"
                value={palettes[index] ? palettes[index].name : ""}
                onKeyUp={(e) => {
                  if (e.key === "Enter") {
                    editingSeedLabel(null);
                  }
                }}
                onBlur={() => editingSeedLabel(null)}
              />
            ) : (
              <div
                className="seed__label"
                onDoubleClick={() => editingSeedLabel(index)}
                style={{
                  color: palettes[selectedSeed]
                    ? palettes[selectedSeed].swatches[6].hex
                    : "black",
                }}>
                {palettes[index] ? palettes[index].name : ""}
              </div>
            )}
          </>
        )}
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Paletteer – Flexible color palettes for digital projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main onClick={() => setColorPickerActive(null)}>
        <div className="header">
          <div
            className="logo"
            style={{
              color: palettes[selectedSeed]
                ? palettes[selectedSeed].swatches[2].hex
                : "#F77777",
            }}>
            <Logo />
          </div>
        </div>
        <div className="controls">
          <div className="seed-colors">
            <p className="seed-colors__label">Seed Colors: </p>
            {seeds.length > 0 ? (
              <>
                {_.map(seeds, (seed, index) => {
                  return (
                    <>
                      <Seed index={index} seed={seed} />
                    </>
                  );
                })}
              </>
            ) : (
              <p className="seed-colors__blank-state">None yet!</p>
            )}
            <button className="seed__add-button" onClick={addColor}>
              <PlusIcon />
            </button>
            {/* <button>Export Colors</button> */}
          </div>
        </div>
        <div className="swatches">
          {palettes.length === 0 && (
            <>
              <h1>Swatches blank state</h1>
            </>
          )}
          {palettes.length > 0 && (
            <>
              {_.map(
                (palettes[selectedSeed] ? palettes[selectedSeed] : []).swatches,
                (swatch, index) => {
                  // Check if this is the selected swatch
                  let selected = index === selectedSwatch;
                  // Check if we should display contrast figures
                  let displayContrast =
                    index === selectedSwatch || index === hoveredSwatch;
                  let swatchStyles = {
                    background: swatch.hex,
                    boxShadow: selected
                      ? "inset 0.25rem 0.25rem 0 rgb(0,0,0,.25)"
                      : "none",
                    transition: `all ease-in-out 0.1s, background ease-in 0.1s ${
                      index * 0.02
                    }s`,
                    padding: selected
                      ? "2.125rem 0.375rem 1.875rem 0.875rem"
                      : "2rem 0.5rem",
                    opacity: colorPickerActive != null ? "0.5" : "1",
                  };
                  let adaptiveTextStyles = { color: swatch.displayColor };
                  let contrastStyles = { opacity: displayContrast ? 1 : 0 };
                  return (
                    <div
                      className="swatch"
                      onClick={() => selectSwatch(index)}
                      onMouseEnter={() => hoverSwatch(index)}
                      onMouseLeave={() => hoverSwatch(null)}>
                      <div className="swatch__body" style={swatchStyles}>
                        <div
                          className="swatch__white-contrast"
                          style={contrastStyles}>
                          <p className="swatch__contrast-text">
                            White Contrast
                          </p>
                          <p
                            className="swatch__contrast-value"
                            style={{ background: "white", color: swatch.hex }}>
                            {swatch.contrastWhite}
                          </p>
                        </div>
                        <div
                          className="swatch__label"
                          style={adaptiveTextStyles}>
                          <p className="swatch__index">
                            {_.padStart(index + 1, 2, "0")}
                          </p>
                          <p className="swatch__hex">{swatch.hex}</p>
                        </div>
                        <div
                          className="swatch__black-contrast"
                          style={contrastStyles}>
                          <p className="swatch__contrast-text">
                            Black Contrast
                          </p>
                          <p
                            className="swatch__contrast-value"
                            style={{ background: "black", color: swatch.hex }}>
                            {swatch.contrastBlack}
                          </p>
                        </div>
                      </div>
                    </div>
                  );
                }
              )}
            </>
          )}
          {colorPickerActive != null && (
            <div className="color-picker__wrapper">
              <div
                className="color-picker"
                onClick={(e) => e.stopPropagation()}>
                <SketchPicker
                  color={
                    palettes[selectedSeed]
                      ? palettes[selectedSeed].swatches[selectedSwatch].hex
                      : "#FFFFFF"
                  }
                  onChangeComplete={updateSeedColor}
                />
              </div>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
